-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- DROP TABLE IF EXISTS song;
CREATE TABLE IF NOT EXISTS account (id SERIAL, username TEXT, password TEXT);
CREATE TABLE IF NOT EXISTS song (id SERIAL, title TEXT, artist TEXT);